kind: Service
apiVersion: v1
metadata:
  name: susi-hangoutbot
  namespace: hangoutbot
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: susi-hangoutbot
  type: LoadBalancer