kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: susi-hangoutbot
  namespace: hangoutbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: susi-hangoutbot
    spec:
      containers:
      - name: susi-hangoutbot
        image: fossasia/susi_hangoutbot:latest-master
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: susi-hangoutbot
      restartPolicy: Always
